// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nscmiutgviorkuucejdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zY21pdXRndmlvcmt1dWNlamRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTQyNDUsImV4cCI6MjA2NjQzMDI0NX0.clO4pBLyoXaZuyMMdw2L7m3yL_DmcX6WRhMIPcC6VBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);